### ISSUE TITLE
from CGAL::Polygon_2<CGAL::Epick> to CGAL::Polygon_2<CGAL::Cartesian<double>>

### ISSUE THREAD

**Issue by TheBlueShy** [Greenzie/boustrophedon_planner#16]
in outline_planner.cpp,   function addInnerOutline,  innermost_polygon = *inner_polygons.front();
error is no known conversion  from CGAL::Polygon_2<CGAL::Epick> to CGAL::Polygon_2<CGAL::Cartesian<double>>
Can you help me with this problem? Thank you very much!

**Comment by Roboprotos** [comment]
Hi, I've got a similar issue when trying to build with CGAL version 5.4 and where there is confusion between CGAL::Cartesian<double> and CGAL::Epick : 
outline_planner.cpp:73:59: error: invalid initialization of reference of type ‘const Point&’ {aka ‘const CGAL::Point_2<CGAL::Cartesian<double> >&’} from expression of type ‘CGAL::Point_2<CGAL::Epick>’
   73 |   for (const Point& p : inner_polygons.front()->container())
   
Did you solve your problem ? Anyone knows why is that issue and if it is a CGAL version problem ?

**Comment by weicyingqiaopian** [comment]
Do you know how to integrate into move_base?
